### ISSUE TITLE
请问怎么判断server已经shutdown，然后重连？

### ISSUE THREAD

**Issue by lazyp** [yedf/openssl-example#1]
目前我用openssl bio连接ssl server，ssl socket server 关闭了，openssl BIO_read返回的是0，但是server关闭了，BIO_write却没任何异常？
具体的描述http://segmentfault.com/q/1010000003808197，能帮忙看下吗？谢谢

**Comment by dtm-labs** [comment]
所有异步编程当中都是这样的行为，就是write正常。你自己必须通过read返回0获知连接关闭。一旦连接关闭，epoll会返回相应socket，对socket进行read会返回0，这样你在连接关闭时立即就得到通知了，然后进行重连

**Comment by lazyp** [comment]
@yedf 但是我发现如果没有及时发现server已经关闭了，如果此时write数据，再调用BIO_free_all会发生段异常。

**Comment by dtm-labs** [comment]
及时发现server已经关闭是你的责任啦，大家编程都是要这么做的，你有什么特别的原因不这么做吗？先要按照正确的方式使用socket IO，如果还有问题，这时才应当去追究为什么还会发生错误

**Comment by dtm-labs** [comment]
实在不行，你把你测试出故障的代码发给我一份，我看看为什么

**Comment by lazyp** [comment]
无法避免的吧，即时write前先read判断，再write那一瞬间server 意外shutdown了呢，发现server shutdown了，会会重试连接server，在连接前先调用BIO_free_all.
代码耦合了整个项目，还有server代码。
大概流程就是这个连接里面写的http://segmentfault.com/q/1010000003808197，能帮忙看下吗？谢谢

**Comment by lazyp** [comment]
你们在用openssl 吗？我们项目server用的netty ，client用的openssl实现。我觉得是无法准确的判断出server是否已经关闭了，先利用read操作判断也是很难保证，在write时server不关闭。
不知道你是否遇到过，write的时候server已经关闭，然后调用BIO_free_all时，进程就自动退出了。
目前进程退出没生成core文件，所以目前也不好判断是异常退出，有可能是正常退出？

**Comment by dtm-labs** [comment]
我们使用openssl没碰见问题。你想要诊断问题最好是编写单独的小例子，看看问题是否复现。

**Comment by lazyp** [comment]
经过debug后，发现底层有一个sigpipe broken pipe信号，程序自己处理忽略这个信号，那么问题解决，再一次write就会正常返回-1 了，而且可以正常调用BIO_free_all函数释放资源，在重新连接server。

**Comment by dtm-labs** [comment]
其实是write就退出了，不是BIO_free_all。恭喜！

**Comment by lazyp** [comment]
en 是的，谢啦！
